### ISSUE TITLE
Normalized Root Mean Squared Error - calculation on train should be test

### ISSUE THREAD

**Issue by benjamin-jacobson** [learn-co-curriculum/dsc-linalg-regression-lab#3]
Please check the solution section "Normalized Root Mean Squared Error", that is being ran using the train, rather than the test data for evaluation/calculation. Suggesting that this should be:

root_mean_sq_err/(y_test.max() - y_test.min())

Nice catch Yeonjoo!

**Comment by zshoorbajee** [comment]
I also came to report this mistake. It looks like it's been open for over two years.

**Comment by christine-egan42** [comment]
Fixed with [85e5e04](https://github.com/learn-co-curriculum/dsc-linalg-regression-lab/commit/85e5e04b7d10ed8858fd15d88a8d57e70c1f16b3)
